### ISSUE TITLE
Errors when running locally

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#163]
When I run the site locally I get this warnings:

```
    Liquid Warning: Liquid syntax error (line 9): Unexpected character   in "{{ content }}" in /_layouts/default.html
    Liquid Warning: Liquid syntax error (line 9): Unexpected character   in "{{ content }}" in /_layouts/default.html
    Liquid Warning: Liquid syntax error (line 9): Unexpected character   in "{{ content }}" in /_layouts/default.html
    Liquid Warning: Liquid syntax error (line 8): Unexpected character   in "{{forloop.index | minus:1 | modulo:4 }}" in articles/index.html
    Liquid Warning: Liquid syntax error (line 9): Unexpected character   in "{{ content }}" in /_layouts/default.html
    Liquid Warning: Liquid syntax error (line 9): Unexpected character   in "{{ content }}" in /_layouts/default.html
    Liquid Warning: Liquid syntax error (line 9): Unexpected character   in "{{ content }}" in /_layouts/default.html
    Liquid Warning: Liquid syntax error (line 9): Unexpected character   in "{{ content }}" in /_layouts/default.html
    Liquid Warning: Liquid syntax error (line 9): Unexpected character   in "{{ content }}" in /_layouts/default.html
    Liquid Warning: Liquid syntax error (line 9): Unexpected character   in "{{ content }}" in /_layouts/default.html
```

Is it possible to remove them? Or they are not a problem?

**Comment by vosaul** [comment]
Yes, I saw it and tried to figure it out, but there was too little information to find the cause. And since everything works, I decided to look for a reason later.

**Comment by vosaul** [comment]
I played around with it a bit. It seems that some libraries are in conflict. The error is caused by all pages without exception. Moreover - the error is caused even by compilation of a blank page - I deleted all pages except one, from this page I deleted all except front matter where I left one field layout: default. And this page (blank!) Also gave a similar error.
Then I updated Jekyll to the latest version and all the dependencies - and those bugs disappeared. There was only one left

But you need to check how it will work when deployed on a real server

![image](https://user-images.githubusercontent.com/28349676/91257868-a0029300-e773-11ea-871d-c9ccaec9aecc.png)

**Comment by davidgatti** [comment]
OK, make the PR and we will see.
