### ISSUE TITLE
The article header

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#181]
Right now when you click the article, the individual article header is zoomed in, and dose not show the full image, would it be possible to display that image in the right proportions?

**Comment by davidgatti** [comment]
This was due to the text

**Comment by edhenderson** [comment]
@davidgatti

This is being caused by the parallax scrolling feature on this image in the template from the theme. It uses `cover` which ensures that the image covers the space intended for it (and then some). Thats how you get the cool 3d effect, see here - https://landkit.goodthemes.co/docs/jarallax.html#backgroundImage

I can disable it to fix your image dimensions, but then you won't get the cool effect.

Not sure on the importance of this to you. Let me know which way you'd like this resolved.

**Comment by edhenderson** [comment]
My opinion, disable the effect and fix the dimensions.

**Comment by davidgatti** [comment]
Yes, let's remove the paralax in this view, it is not necessary.
