### ISSUE TITLE
The header jump when you load the page

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#243]
I don't know if this is going to show up on your side. But when you load the Schedule and Contact page, the image header jumps, and adjust itself, something that is not happening in the Article page. Please check it out to see what is going on. 

I'm doing this on Chrome, and if you don't have the same experience I can make a video.

**Comment by edhenderson** [comment]
I shall investigate. Understood.

**Comment by edhenderson** [comment]
I can see something going on.

**Comment by edhenderson** [comment]
This is caused by the parallax library (took a while to track this down). Essentially what it does is that it takes a background image, e.g. articles.jpg and then through script replaces it with the parallax version (so you get this flash). The flash is the initial image loading, disappearing and the new one coming in.
