### ISSUE TITLE
Snap text to the top margin

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#288]
When there is little text, then the text is lower then it should be.

![Screen Shot 2021-03-06 at 11 27 08 AM](https://user-images.githubusercontent.com/411114/110203901-bbf89700-7e70-11eb-97a1-0d13d104dfc6.png)

**Comment by edhenderson** [comment]
I understand what you are asking but not sure exactly how to implement it. The left hand side is made with padding:

<img width="729" alt="Screenshot 2021-03-09 at 21 01 48" src="https://user-images.githubusercontent.com/1378582/110537829-203e8380-811b-11eb-8016-e6ddc9f50384.png">

The red dotted line you've drawn doesn't really exist because the top of the image isn't a tangible point:

<img width="756" alt="Screenshot 2021-03-09 at 21 02 22" src="https://user-images.githubusercontent.com/1378582/110537916-419f6f80-811b-11eb-8586-b047ccdae44d.png">

Let me know if my explanation exists and what you'd like me to do?

**Comment by edhenderson** [comment]
@davidgatti I shall investigate.
